name: Build and Release
on: push

jobs:
  weasyprint-build-arm64:
    name: Build WeasyPrint arm64
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        version: ["3.12", "3.13"]
    env:
      RUNTIME: ${{ matrix.version }}
      PLATFORM: linux/arm64
      ARCH: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer 
        run: make build/weasyprint-layer-python${{ matrix.version }}-arm64.zip
      - name: Test weasyprint
        run: |
          mkdir output
          make test.start.container &
          sleep 1
          make test.print.report
          rm -rf build/opt
        env:
          TEST_FILENAME: build/test-report-${{ matrix.version }}-arm64.pdf 
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WeasyPrint Layer Build ${{ matrix.version }}
          path: build
  weasyprint-build-x86_64:
    name: Build WeasyPrint x86_64
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        version: ["3.12", "3.13"]
    env:
      RUNTIME: ${{ matrix.version }}
      PLATFORM: linux/amd64
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer 
        run: make build/weasyprint-layer-python${{ matrix.version }}-x86_64.zip
      - name: Test weasyprint
        run: |
          mkdir output
          make test.start.container &
          sleep 1
          make test.print.report
          rm -rf build/opt
        env:
          TEST_FILENAME: build/test-report-${{ matrix.version }}-x86_64.pdf 
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: WeasyPrint Layer Build ${{ matrix.version }}
          path: build
  weasyprint-release:
    name: Release WeasyPrint
    runs-on: ubuntu-24.04-arm
    needs: [weasyprint-build-arm64, weasyprint-build-x86_64]
    if: startsWith(github.ref, 'refs/tags/weasyprint-')
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create WeasyPrint Release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: ./artifacts/**/weasyprint-layer-python*

  ghostscript-build:
    name: Build GhostScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Layer
        run: |
          make build/ghostscript-layer.zip
          rm -rf build/opt
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: GhostScript Layer Build
          path: build
      - name: Create GhostScript Release
        if: startsWith(github.ref, 'refs/tags/ghostscript-')
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          files: ./build/ghostscript-layer.zip
